### ISSUE TITLE
Device Registration no longer works

### ISSUE THREAD

**Issue by gwgorman** [ibm-watson-iot/gateway-smartthings#4]
the app tries to use bulk creation APIs but I believe that has all changed since this was written. Needs update.

**Comment by durera** [comment]
It should still work .. I've updated the SmartApp running in my house today to test and can see that the `metadata.bridge.version` updated from version `0.4.0` to `0.4.1` as expected:

```
cddbbce8-d3da-432c-8c77-1578dae2cafc  1:36:57 PM: info RegisterDevices() - All devices registered, subscribing to device events
cddbbce8-d3da-432c-8c77-1578dae2cafc  1:36:56 PM: trace upsertDevices: https://hldtxx.internetofthings.ibmcloud.com/api/v0002/bulk/devices/upsert
```

Does the API key you are using have the necessary role/permissions to call the bulk add/delete/upsert APIs?

Can you try the following using your preferred API tester (postman/whatever) to confirm that the API key has the necessary scope:

POST: `https://YOURORGID.internetofthings.ibmcloud.com/api/v0002/bulk/devices/upsert`

Headers: `Content-Type: application/json`
Body: 
```
[
	{"typeId": "test", "deviceId": "1", "metadata": {"foo": "bar"}},
	{"typeId": "test", "deviceId": "2", "metadata": {"foo": "bar"}}
]
```

**Comment by gwgorman** [comment]
hi David, 
I get a 
403 Forbidden
Time:285 ms
Size:252 B

as the reply from Postman. 

I have a free account. tagged as an IBM employee, the IoTP plan I have is "Standard" 

Assuming there is something I can set/change on the platform to enable it? 

/Greg

**Comment by gwgorman** [comment]
looking at the IoTP API key page I have this one set to "device application". What should it be set to?

**Comment by durera** [comment]
Check what role your API key has, and what permissions are associated with that role ... if you are getting 403 your API key does not have necessary permissions to register devices

https://YOURORGID.internetofthings.ibmcloud.com/dashboard/#/accessmanagement/roles

![image](https://user-images.githubusercontent.com/4400618/43586542-cf2df7ee-965f-11e8-9d34-0a21d69d1445.png)


Of the default roles, you need to be using an API key with `Backend Trusted Application`,  or `Standard Application` so that you have both the abilty to register devices and submit events on behalf of devices.

**Comment by gwgorman** [comment]
ok that's what fixed it - changed it to Standard Application and that took care of it! 

Thanks! 
/gg
