### ISSUE TITLE
5-minute update not working

### ISSUE THREAD

**Issue by gwgorman** [ibm-watson-iot/gateway-smartthings#5]
docs state "State updates are published to Watson IoT in real time and captured every 5 minutes even when no state changes have occured."

I don't see those coming through to WIoTP nor do I see anything in the code that would imply a 5-minute status update. I seem to only get data from any sensor when it senses a change and that's about it. 

Perhaps this was a TODO? :)

**Comment by durera** [comment]
Looks like I forgot to remove that from the README.  

It was originally a capability of the bridge, but this commit (https://github.com/ibm-watson-iot/gateway-smartthings/commit/a650b24a707b5b082936b2bd1376e92656daecd3#diff-1fa1c364bbf2abd3cafd8ebce8aec7a7) removed the `syncEverything()` feature that was called on interval -- because it did not scale well when large number of devices were registered to the hub.

It was a while ago now but IIRC I was continually running into the 20 second smartapp runtime limit, and breaking the sync into smaller and smaller chunks, eventually I hit the point where I figured, this is unnecessary -- if nothing has changed in smartthings then the last state that was sent is still available in Watson IoT anyway (via the last event cache), so I was creating problems that didn't really need to be fought, the only gap it left was when something new was registered would have no state in Watson IoT until the first change in state on SmartThings side.

Is the regular sync something you think you need in your use-case?

**Comment by gwgorman** [comment]
I think we need a full update at least once on Initialize() or something. It could take days and days before a new device registers something (or hopefully never if it's a moisture sensor...). A bit unnerving if you have a dashboard full of NO DATA flags instead of "last reported status". 
I'm connected to Node-RED and using the IoTP node there and watching what is coming over.

**Comment by durera** [comment]
A staggered one time sync shouldn't be a problem.  I'll take a look when I get a chance, unless you want to make the changes and submit a PR?

**Comment by gwgorman** [comment]
will take a look and let you know.
